spring.application.name=simple_web_app
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/simple_web_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=michael

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true
